# Generated by Django 2.2 on 2019-04-06 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='athlete',
            name='height',
            field=models.IntegerField(default=175),
        ),
    ]
