# Generated by Django 2.2 on 2019-04-08 01:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_location_run'),
    ]

    operations = [
        migrations.AddField(
            model_name='athlete',
            name='runs',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.Run'),
        ),
    ]
