# Generated by Django 2.2 on 2019-04-08 01:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_athlete_runs'),
    ]

    operations = [
        migrations.CreateModel(
            name='RunSplits',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dist', models.FloatField()),
                ('t', models.FloatField()),
                ('heartrate', models.IntegerField(default=0)),
                ('notes', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='run',
            name='location',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.Location'),
        ),
    ]
