# Generated by Django 2.2 on 2019-04-08 01:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20190407_1854'),
    ]

    operations = [
        migrations.CreateModel(
            name='RunSplit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dist', models.FloatField()),
                ('t', models.FloatField()),
                ('heartrate', models.IntegerField(default=0)),
                ('notes', models.TextField(null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='RunSplits',
        ),
        migrations.AddField(
            model_name='run',
            name='splits',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.RunSplit'),
        ),
    ]
